export const attentionCategories = ['AI Tools','SaaS','Developer Tools','Marketing','Productivity','Apps','Finance','Design','Education','Gaming','Other'];
export type Bid = {id:string;amount:number;createdAt:number};
export type CampaignPreview = {title:string;description:string;requirements:string;budget:number;existingCampaignId?:string};
export type Product = {id:string;brandId:string;brandName:string;name:string;slug:string;logo:string;color:string;websiteUrl:string;description:string;category:string;tags:string[];currentBid:number;clickCount:number;visitTimes:number[];status:'active'|'expired';listingStartsAt:number;listingEndsAt:number;campaign?:CampaignPreview;bids:Bid[]};
export type ActivityEvent = {id:string;productId:string;type:'bid'|'listing'|'visit';createdAt:number;amount?:number;rank?:number};
export type MarketplaceFilters = {query:string;category:string;time:'all'|'48h'};
export type MarketplaceState = {version:1;products:Product[];activity:ActivityEvent[]};
export type MarketplaceStats = {activeProducts:number;visitsToday:number;weeklyBids:number};
export const LISTING_FEE=10;
export const LISTING_DAYS=7;
export function isActive(p:Product, now=Date.now()){return p.status==='active'&&p.listingStartsAt<=now&&p.listingEndsAt>now;}
export function getRankedProducts(products:Product[],now=Date.now()){return products.filter(p=>isActive(p,now)).slice().sort((a,b)=>b.currentBid-a.currentBid||(a.bids[0]?.createdAt??a.listingStartsAt)-(b.bids[0]?.createdAt??b.listingStartsAt)||a.id.localeCompare(b.id));}
export function getMinimumBidForPosition(products:Product[],productId:string,now=Date.now()){const ranked=getRankedProducts(products,now);const i=ranked.findIndex(p=>p.id===productId);if(i<0)return null;const current=ranked[i].currentBid;const nextHigher=i>0?ranked[i-1].currentBid:current;return nextHigher-current+1;}
export function getProjectedRank(products:Product[],amount:number,productId?:string,now=Date.now()){return getRankedProducts(products,now).filter(p=>p.id!==productId&&p.currentBid>=amount).length+1;}
export function getFilteredProducts(products:Product[],filters:MarketplaceFilters,now=Date.now()){const q=filters.query.trim().toLowerCase();return getRankedProducts(products,now).filter(p=>(filters.category==='All'||p.category===filters.category||p.tags.includes(filters.category))&&(!q||`${p.name} ${p.brandName} ${p.description} ${p.category} ${p.tags.join(' ')}`.toLowerCase().includes(q))&&(filters.time==='all'||Math.max(p.listingStartsAt,p.bids[0]?.createdAt??0)>=now-48*3600000));}
export function getMarketplaceStats(products:Product[],now=Date.now()):MarketplaceStats{const active=getRankedProducts(products,now);const midnight=new Date(now);midnight.setHours(0,0,0,0);return {activeProducts:active.length,visitsToday:products.reduce((s,p)=>s+p.visitTimes.filter(t=>t>=midnight.getTime()&&t<=now).length,0),weeklyBids:products.reduce((s,p)=>s+p.bids.filter(b=>b.createdAt>=now-7*86400000&&b.createdAt<=now).reduce((n,b)=>n+b.amount,0),0)};}
export function validateBid(products:Product[],id:string,increment:number,now=Date.now()){const p=products.find(p=>p.id===id);if(!p||!isActive(p,now))return 'This listing has expired and cannot receive bids.';if(!Number.isFinite(increment)||increment<=0)return 'Enter a valid bid amount.';if(!Number.isInteger(increment))return 'Use a whole-dollar amount.';const nextBid=p.currentBid+increment;if(nextBid>100000)return 'Demo bids must be $100,000 or less.';const min=getMinimumBidForPosition(products,id,now)!;if(increment<min)return `Enter at least $${min} to improve this product’s position.`;return '';}
export function timeAgo(timestamp:number,now=Date.now()){const hours=Math.max(0,Math.floor((now-timestamp)/3600000));return hours>=24?`${Math.floor(hours/24)}d ago`:hours?`${hours}h ago`:Math.max(0,Math.floor((now-timestamp)/60000))<1?'Just now':`${Math.floor((now-timestamp)/60000)}m ago`;}
export function safeWebsite(value:string){try{if(typeof value!=='string'||value.length>2048)return null;const trimmed=value.trim();if(!trimmed||trimmed.length>2048||/\s/.test(trimmed))return null;const u=new URL(trimmed);const host=u.hostname.toLowerCase();if(!['https:','http:'].includes(u.protocol)||u.username||u.password||!host)return null;if(host==='localhost'||host==='127.0.0.1'||host==='0.0.0.0'||host==='::1')return null;return u.href;}catch{return null;}}
export function websiteHost(value:string){const href=safeWebsite(value);if(!href)return '';try{return new URL(href).hostname;}catch{return '';}}
