'use client';
import React from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Orbit,Layers,Command,Zap,Code2,Search,Check,Inbox,Camera,Star} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Campaign,money} from '../data';
export function Logo({white=false}:{white?:boolean}){return <Link href="/" className={`logo ${white?'white':''}`} aria-label="GoHIGHnet home"><img className="brand-logo-image" src="/logo.PNG" alt="" width={42} height={42}/>GoHIGH<span className="logo-light">net</span></Link>}
export function Button({children,variant='primary',className='',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger'}){return <button className={`btn btn-${variant} ${className}`} {...props}>{children}</button>}
export function Pick({value,onChange,options,label,className=''}:{value:string;onChange:(v:string)=>void;options:string[];label?:string;className?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label||'Choose an option'} className={`pick ${className}`}><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>}
export function Field({label,hint,children,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;hint?:string;children?:React.ReactNode}){return <label className="field"><span>{label}{props.required&&<b> *</b>}</span>{children||<input {...props}/>} {hint&&<small>{hint}</small>}</label>}
export function Textarea({label,...props}:React.TextareaHTMLAttributes<HTMLTextAreaElement>&{label:string}){return <label className="field"><span>{label}{props.required&&<b> *</b>}</span><textarea {...props}/></label>}
export function Modal({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description?:string;children:React.ReactNode;wide?:boolean}){return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className={`app-modal ${wide?'wide':''}`}><DialogTitle>{title}</DialogTitle><DialogDescription>{description||'Review the details below.'}</DialogDescription>{children}</DialogContent></Dialog>}
export function Confirm({open,onClose,onConfirm,title,description,label='Confirm'}:{open:boolean;onClose:()=>void;onConfirm:()=>void;title:string;description:string;label?:string}){return <AlertDialog open={open} onOpenChange={v=>!v&&onClose()}><AlertDialogContent className="app-modal"><AlertDialogTitle>{title}</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel onClick={onClose}>Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>{onConfirm();onClose()}}>{label}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
export function PageTitle({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:React.ReactNode}){return <div className="page-title"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}<span>.</span></h1>{description&&<p>{description}</p>}</div>{children&&<div className="title-actions">{children}</div>}</div>}
export function SearchBox({value,onChange,placeholder='Search…'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="search-box"><Search size={18}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/></label>}
export function ViewTabs({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <Tabs value={value} onValueChange={onChange}><TabsList variant="line" className="view-tabs">{options.map(x=><TabsTrigger key={x.value} value={x.value}>{x.label}</TabsTrigger>)}</TabsList></Tabs>}
export function Empty({title,description,children}:{title:string;description:string;children?:React.ReactNode}){return <div className="empty-state"><span><Inbox size={30}/></span><h3>{title}</h3><p>{description}</p>{children}</div>}
const icons:Record<string,any>={orbit:Orbit,stack:Layers,frame:Command,flow:Zap,code:Code2,launch:ArrowUpRight};
export function Mark({c,size=''}:{c:Campaign;size?:string}){const I=icons[c.letter]||Layers;return <span className={`brand-mark ${size}`} style={{background:c.color}}><I size={25}/></span>}
export function Avatar({name,color='#e8eeff',image,size=''}:{name:string;color?:string;image?:string;size?:string}){return <span className={`avatar ${size}`} style={{background:color}}>{image?<img src={image} alt="Profile"/>:name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()||'Y'}</span>}
export function Platform({name}:{name:string}){return <span className="platform">{name==='Instagram'?<Instagram size={14}/>:name==='Facebook'?<Facebook size={14}/>:<span className="x-logo">𝕏</span>}{name==='X'?'X / Twitter':name}</span>}
export function Rating({value,count}:{value:number;count?:number}){return <span className="rating"><Star size={14} fill="currentColor"/>{value.toFixed(1)}{count!==undefined&&<small>({count})</small>}</span>}
export const statusLabels:Record<string,string>={pending:'Pending request',negotiating:'In negotiation','awaiting-funds':'Awaiting payment','in-progress':'In progress','in-review':'In review',revision:'Changes requested',completed:'Completed',declined:'Declined',disputed:'Under review',active:'Active',draft:'Draft',paused:'Paused',expired:'Expired'};
export function Status({status}:{status:string}){return <span className={`status status-${status}`}>{statusLabels[status]||status}</span>}
export function DemoNote({children}:{children?:React.ReactNode}){return <div className="demo-note"><span className="tiny-dot"/>{children||'Frontend preview · Sample data · No real payments or messages are sent.'}</div>}
export function MoneyRange({c}:{c:Campaign}){return <div className="money-range"><strong>{money(c.budget)}–{money(c.maxBudget)}</strong><small>per collaboration</small></div>}
export function download(name:string,text:string,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
export function validURL(v:string){try{return ['http:','https:'].includes(new URL(v).protocol)}catch{return false}}

export function Instagram({size=18,...props}:{size?:number;[key:string]:any}){return <Camera size={size} {...props}/>;}
export function Facebook({size=18,...props}:{size?:number;[key:string]:any}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" {...props}><text x="7" y="22" fontSize="25" fontWeight="bold" fontFamily="Arial">f</text></svg>;}
